# -*- coding: utf-8 -*-
"""Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNx1cVm7Ex_m0zFqUEWXAta0q54d5m9c
"""

letras = ["a", "b", "e", "f", "o", "x", "c"]

for n in letras:
  if n == "a" or n == "e" or n == "i" or n == "o" or n == "u":
    print(n, True)
  else:
    print(n, False)

letras = ["a", "b", "e", "f", "o", "x", "c"]
vocales = ("a", "e", "i", "o", "u")

for n in letras:
  if n in vocales:
    print(n, True)
  else:
    print(n, False)

experiencias = [1, 5, 3, 2, 7, 4, 3, 6, 2, 5]
experiencia3 = []
experienciaImpar = []

for n in experiencias:
  if n >= 3:
    experiencia3.append(n)
  if n % 2 != 0:
    experienciaImpar.append(n)

print(f"Mas de tres años de experiencia: {experiencia3}")
print(f"Experiencia Impar: {experienciaImpar}")

skills = ["Python", "Excel", "Communication", "Java", "SQL","Project Management", "Python", "JavaScript", "Excel", "Leadership"]
userSkill = input("Que skill tienes? ")

if userSkill in skills:
  print("Has sido contratado")
else:
  print("No cumples los requesitos")

texto = "       programazioa GUSTATZEN zait########"

texto = texto.lower()
texto = texto.lstrip()
texto = texto.rstrip("#")
print(texto)

print(texto.upper())

texto.capitalize()

print(texto.strip() + "XXXX")

print("YYYY" + texto.strip("#") + "XXXXXXX")

texto.replace("zait", "zaio")

texto1 = "Hello, Goodbye, Morning"
texto2 = "Kaixo,Agur"

x, y, z = texto1.split(", ")
print(x)
print(y)
print(z)

print(f"{x}, {y}, {z}")