# -*- coding: utf-8 -*-
"""strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199cdpmaEbfs9C31yOGl18x9jV-rtX-2k

#Mi pryecto en la nube
**Mi primer programa**

hay que pinchar la flecha para que se ejecuta.

Requisitos:
aaa


*   aaa
*   bbb
"""

print('Programa de Python')

texto = "programazioa gustatzen zait"
print(texto[13:22])

s = 'Me encanta python'

if 'python' in s:
  print('python existe')

texto = '     122,python,es,4444,un,LENGUAJE,333,de,9999,programacion   '

texto = texto.strip()
lista = texto.split(',')
for l in lista:
  if l.isnumeric():
    lista.remove(l)

texto = ''.join(lista).lower().capitalize()
print(texto)

"""# Ejercicio 1
*Un usuaurio ha introducido su nombre como:*

`nombre = "     jUAn     "`

Mostrar el resultado como 'Juan'.
"""

nombre = '      jUAn      '
nombre = nombre.strip().lower().capitalize()
print(nombre)

"""# Ejercicio 2
*Tienes un mensaje donde una palabra aparece varias veces.*

`mensaje = "Hola a todos todos todos"`

Remplezar todos por TODOS.
"""

mensaje = 'Hola a todos todos todos'
mensaje = mensaje.replace('todos', 'TODOS')
print(mensaje)

"""# Ejercicio 3
`nombre_completo = "jon#smith"`

Separar nombre_completo en variables **nombre** y **completo**.
"""

nombreCompleto = 'Jon#Smith'
nombre, completo = nombreCompleto.split('#')
print(nombre)
print(completo)

"""# Ejercicio 4 (Ejercicio Avanzado)
`s = "XXXXXHOY;donostian;$;TARDE;bizi;%;IDEAL;1;5;naiz;2;LEER;LIBROXXXXX"`

Queremos quitar todo excepto las palabras en lowercase, por ejemplo: donostian bizi naiz, y presentarles al final : "Donostian bizi naiz."
"""

lista1 = []
lista2 = []
s = "XXXXXHOY;donostian;$;TARDE;bizi;%;IDEAL;1;5;naiz;2;LEER;LIBROXXXXX"
lista1 = s.split(';')
for l in lista1:
  if l.islower():
    lista2.append(l)
  else:
    pass

s = ' '.join(lista2).capitalize()
print(s)